---
name: Code Quality

# This workflow is triggered on pushes to the repository.
on:
  pull_request:
    branches:
      - master
      - develop
  push:
    branches:
      - master
      - develop
      - "bugfix/**"
      - "feature/**"
      - "release/**"
    tags:
      - v.*

jobs:
  build:
    name: Lint with pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1.4.3
        with:
          node-version: "12"
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - uses: actions/setup-go@v2
        with:
          go-version: "1.14"
      - name: Install dependencies
        run: |
          pip3 install -r requirements.dev.txt
          GO111MODULE=on go get mvdan.cc/sh/v3/cmd/shfmt
          sudo apt-get install -y shellcheck
          python --version
          shfmt -version
          shellcheck --version
          pre-commit --version
      - name: Cache pre-commit dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pre-commit/
          # yamllint disable-line rule:line-length
          key: ${{ runner.os }}-pre-commit-${{ hashFiles('**/.pre-commit-config.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pre-commit-
      - name: Run pre-commit
        run: pre-commit run -a
