---
- name: Install pyenv build requirements with Homebrew
  homebrew:
    name: "{{ pyenv_build_requirements_with_homebrew }}"

- name: Detect existing pyenv install
  include_tasks: detect_existing_install.yml
  when: pyenv_detect_existing_install|bool

- name: Install with Homebrew
  include_tasks: install_with_homebrew.yml
  when: pyenv_install_from_package_manager|bool

- name: Uninstall Homebrew packages
  include_tasks: remove_homebrew.yml
  when: not pyenv_install_from_package_manager|bool

- name: Install with Git
  include_tasks: install_with_git.yml
  when: not pyenv_install_from_package_manager|bool
