---
- name: Remove readline from Homebrew on Linux
  homebrew:
    name: readline
    state: absent
    install_options: "ignore-dependencies"
    path: "{{ pyenv_brew_path | default(omit) }}"
  register: pyenv_brew_readline_uninstall
  changed_when: false
  when: >-
    ansible_system == 'Linux'
    and pyenv_homebrew_on_linux | bool

- name: Unlink Homebrew OpenSSL on Linux
  homebrew:
    name: openssl
    state: unlinked
    path: "{{ pyenv_brew_path | default(omit) }}"
  register: pyenv_brew_openssl_unlink
  changed_when: false
  when: >-
    ansible_system == 'Linux'
    and pyenv_homebrew_on_linux | bool
    and pyenv_homebrew_openssl_fix | bool

- name: Install Python interpreters
  shell: >-
    . {{ pyenv_root }}/.pyenvrc &&
    pyenv install {{ item }}
  args:
    executable: "{{ pyenv_install_shell | default(omit) }}"
    creates: "{{ pyenv_root }}/versions/{{ item }}/bin/python"
  with_items: "{{ pyenv_python_versions }}"
  environment: "{{ pyenv_install_environment }}"

- name: Install readline with Homebrew on Linux # noqa 503
  homebrew:
    name: readline
    state: present
    path: "{{ pyenv_brew_path | default(omit) }}"
  changed_when: false
  when: >-
    ansible_system == 'Linux'
    and pyenv_homebrew_on_linux | bool
    and pyenv_brew_readline_uninstall is defined
    and pyenv_brew_readline_uninstall.changed

- name: Link Homebrew OpenSSL on Linux # noqa 503
  homebrew:
    name: openssl
    state: linked
    path: "{{ pyenv_brew_path | default(omit) }}"
  changed_when: false
  when: >-
    ansible_system == 'Linux'
    and pyenv_homebrew_on_linux | bool
    and pyenv_homebrew_openssl_fix | bool
    and pyenv_brew_openssl_unlink is defined
    and pyenv_brew_openssl_unlink.changed

- name: Get current global version
  shell: >-
    . {{ pyenv_root }}/.pyenvrc &&
    pyenv global
  args:
    executable: "{{ pyenv_install_shell | default(omit) }}"
  register: pyenv_global_version
  changed_when: false

- name: Set pyenv_global_active fact
  set_fact:
    pyenv_global_active: "{{ pyenv_global_version.stdout_lines |
      join(' ') | trim() }}"

- name: Check if 'system' version is available
  shell: >-
    set -o pipefail &&
    . {{ pyenv_root }}/.pyenvrc &&
    pyenv versions | grep -q system
  args:
    executable: "{{ pyenv_install_shell | default(omit) }}"
  register: pyenv_versions_grep_system
  changed_when: false
  failed_when: false
  when: "'system' in pyenv_global"

- name: Remove 'system' from pyenv_global
  set_fact:
    pyenv_global: "{{ pyenv_global | replace('system', '') | trim() }}"
  when: "'system' in pyenv_global and pyenv_versions_grep_system.rc != 0"

- name: Set pyenv global version to '{{ pyenv_global }}'
  shell: >-
    . {{ pyenv_root }}/.pyenvrc &&
    pyenv global {{ pyenv_global }} &&
    pyenv rehash
  args:
    executable: "{{ pyenv_install_shell | default(omit) }}"
  when: "pyenv_global is defined and pyenv_global_active != pyenv_global"
