---
- name: Set path to .bashrc
  set_fact:
    pyenv_bashrc_path: "{{ pyenv_home }}/.bashrc"
  when: pyenv_bashrc_path is undefined

- name: Check whether .bashrc file exists
  stat:
    path: "{{ pyenv_bashrc_path }}"
  register: pyenv_bashrc_st

- name: Resolve .bashrc symlink
  set_fact:
    pyenv_bashrc_path: "{{ pyenv_bashrc_st.stat.lnk_source }}"
  when: pyenv_bashrc_st.stat.exists and pyenv_bashrc_st.stat.islnk

- name: Check whether .pyenvrc is loaded in .bashrc
  command: grep -EFq 'source $HOME/.pyenv/.pyenvrc' {{ pyenv_bashrc_path }}
  register: check_bashrc
  ignore_errors: true
  changed_when: false
  failed_when: false
  when: pyenv_bashrc_st.stat.exists

- name: Load pyenv in .bashrc
  blockinfile:
    dest: "{{ pyenv_bashrc_path }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: pyenv"
    block: |
      if [ -e "$HOME/.pyenv/.pyenvrc" ]; then
        source $HOME/.pyenv/.pyenvrc
        if [ -e "$HOME/.pyenv/completions/pyenv.bash" ]; then
          source $HOME/.pyenv/completions/pyenv.bash
        elif [ -e "/usr/local/opt/pyenv/completions/pyenv.bash" ]; then
          source /usr/local/opt/pyenv/completions/pyenv.bash
        fi
      fi
  when: pyenv_bashrc_st.stat.exists and check_bashrc.rc != 0

- name: Set path to .zshrc
  set_fact:
    pyenv_zshrc_path: "{{ pyenv_home }}/.zshrc"
  when: pyenv_zshrc_path is undefined

- name: Check whether .zshrc exists
  stat:
    path: "{{ pyenv_zshrc_path }}"
  register: pyenv_zshrc_st

- name: Resolve .zshrc symlink
  set_fact:
    pyenv_zshrc_path: "{{ pyenv_zshrc_st.stat.lnk_source }}"
  when: pyenv_zshrc_st.stat.exists and pyenv_zshrc_st.stat.islnk

- name: Check whether .pyenvrc is loaded in .zshrc
  command: grep -Fq 'source $HOME/.pyenv/.pyenvrc' {{ pyenv_zshrc_path }}
  register: check_zshrc
  ignore_errors: true
  changed_when: false
  failed_when: false
  when: pyenv_zshrc_st.stat.exists

- name: Load pyenv in .zshrc
  blockinfile:
    dest: "{{ pyenv_zshrc_path }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: pyenv"
    block: |
      if [ -e "$HOME/.pyenv/.pyenvrc" ]; then
        source $HOME/.pyenv/.pyenvrc
        if [ -e "$HOME/.pyenv/completions/pyenv.zsh" ]; then
          source $HOME/.pyenv/completions/pyenv.zsh
        elif [ -e "/usr/local/opt/pyenv/completions/pyenv.zsh" ]; then
          source /usr/local/opt/pyenv/completions/pyenv.zsh
        fi
      fi
  when: pyenv_zshrc_st.stat.exists and check_zshrc.rc != 0
